// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.2
// source: borrow.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BorrowService_BorrowABook_FullMethodName           = "/borrowpb.BorrowService/BorrowABook"
	BorrowService_ReturnBook_FullMethodName            = "/borrowpb.BorrowService/ReturnBook"
	BorrowService_GetAllBorrows_FullMethodName         = "/borrowpb.BorrowService/GetAllBorrows"
	BorrowService_GetAllNotReturnedBook_FullMethodName = "/borrowpb.BorrowService/GetAllNotReturnedBook"
)

// BorrowServiceClient is the client API for BorrowService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BorrowServiceClient interface {
	BorrowABook(ctx context.Context, in *BorrowedBookRequest, opts ...grpc.CallOption) (*WebResponse, error)
	ReturnBook(ctx context.Context, in *UpdateBorrowedBook, opts ...grpc.CallOption) (*WebResponse, error)
	GetAllBorrows(ctx context.Context, in *UserId, opts ...grpc.CallOption) (*WebResponse, error)
	GetAllNotReturnedBook(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*WebResponse, error)
}

type borrowServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBorrowServiceClient(cc grpc.ClientConnInterface) BorrowServiceClient {
	return &borrowServiceClient{cc}
}

func (c *borrowServiceClient) BorrowABook(ctx context.Context, in *BorrowedBookRequest, opts ...grpc.CallOption) (*WebResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WebResponse)
	err := c.cc.Invoke(ctx, BorrowService_BorrowABook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *borrowServiceClient) ReturnBook(ctx context.Context, in *UpdateBorrowedBook, opts ...grpc.CallOption) (*WebResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WebResponse)
	err := c.cc.Invoke(ctx, BorrowService_ReturnBook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *borrowServiceClient) GetAllBorrows(ctx context.Context, in *UserId, opts ...grpc.CallOption) (*WebResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WebResponse)
	err := c.cc.Invoke(ctx, BorrowService_GetAllBorrows_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *borrowServiceClient) GetAllNotReturnedBook(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*WebResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WebResponse)
	err := c.cc.Invoke(ctx, BorrowService_GetAllNotReturnedBook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BorrowServiceServer is the server API for BorrowService service.
// All implementations must embed UnimplementedBorrowServiceServer
// for forward compatibility.
type BorrowServiceServer interface {
	BorrowABook(context.Context, *BorrowedBookRequest) (*WebResponse, error)
	ReturnBook(context.Context, *UpdateBorrowedBook) (*WebResponse, error)
	GetAllBorrows(context.Context, *UserId) (*WebResponse, error)
	GetAllNotReturnedBook(context.Context, *Empty) (*WebResponse, error)
	mustEmbedUnimplementedBorrowServiceServer()
}

// UnimplementedBorrowServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBorrowServiceServer struct{}

func (UnimplementedBorrowServiceServer) BorrowABook(context.Context, *BorrowedBookRequest) (*WebResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BorrowABook not implemented")
}
func (UnimplementedBorrowServiceServer) ReturnBook(context.Context, *UpdateBorrowedBook) (*WebResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReturnBook not implemented")
}
func (UnimplementedBorrowServiceServer) GetAllBorrows(context.Context, *UserId) (*WebResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllBorrows not implemented")
}
func (UnimplementedBorrowServiceServer) GetAllNotReturnedBook(context.Context, *Empty) (*WebResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllNotReturnedBook not implemented")
}
func (UnimplementedBorrowServiceServer) mustEmbedUnimplementedBorrowServiceServer() {}
func (UnimplementedBorrowServiceServer) testEmbeddedByValue()                       {}

// UnsafeBorrowServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BorrowServiceServer will
// result in compilation errors.
type UnsafeBorrowServiceServer interface {
	mustEmbedUnimplementedBorrowServiceServer()
}

func RegisterBorrowServiceServer(s grpc.ServiceRegistrar, srv BorrowServiceServer) {
	// If the following call pancis, it indicates UnimplementedBorrowServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BorrowService_ServiceDesc, srv)
}

func _BorrowService_BorrowABook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BorrowedBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BorrowServiceServer).BorrowABook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BorrowService_BorrowABook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BorrowServiceServer).BorrowABook(ctx, req.(*BorrowedBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BorrowService_ReturnBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBorrowedBook)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BorrowServiceServer).ReturnBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BorrowService_ReturnBook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BorrowServiceServer).ReturnBook(ctx, req.(*UpdateBorrowedBook))
	}
	return interceptor(ctx, in, info, handler)
}

func _BorrowService_GetAllBorrows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BorrowServiceServer).GetAllBorrows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BorrowService_GetAllBorrows_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BorrowServiceServer).GetAllBorrows(ctx, req.(*UserId))
	}
	return interceptor(ctx, in, info, handler)
}

func _BorrowService_GetAllNotReturnedBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BorrowServiceServer).GetAllNotReturnedBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BorrowService_GetAllNotReturnedBook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BorrowServiceServer).GetAllNotReturnedBook(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// BorrowService_ServiceDesc is the grpc.ServiceDesc for BorrowService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BorrowService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "borrowpb.BorrowService",
	HandlerType: (*BorrowServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BorrowABook",
			Handler:    _BorrowService_BorrowABook_Handler,
		},
		{
			MethodName: "ReturnBook",
			Handler:    _BorrowService_ReturnBook_Handler,
		},
		{
			MethodName: "GetAllBorrows",
			Handler:    _BorrowService_GetAllBorrows_Handler,
		},
		{
			MethodName: "GetAllNotReturnedBook",
			Handler:    _BorrowService_GetAllNotReturnedBook_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "borrow.proto",
}
